In [26]:
import pandas as pd

In [27]:
df_c = pd.read_csv('covid_count_data.csv')
df_gender = pd.read_csv('gender_data.csv')
df_age = pd.read_csv('age_data.csv')
df_area = pd.read_csv('area_data.csv')

In [28]:
df = pd.merge(df_c, df_gender, how='outer',on='date')

In [29]:
df = pd.merge(df, df_age, how='outer',on='date')
df

,date,overseas,domestic,confirmed,iso,iso_rel,death,m_confirmed,m_death,f_confirmed,...,40s_confirmed,40s_death,50s_confirmed,50s_death,60s_confirmed,60s_death,70s_confirmed,70s_death,80s_over_confirmed,80s_over_death
0,2020-02-03,0,0,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-04,0,0,18,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-05,0,0,19,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-06,0,0,23,0,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-07,0,0,24,0,2,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,2020-10-24,11,66,25775,1484,23834,457,12003.0,244.0,13772.0,...,3448.0,4.0,4738.0,21.0,4118.0,53.0,2075.0,147.0,1115.0,230.0
265,2020-10-25,11,50,25836,1510,23869,457,12029.0,244.0,13807.0,...,3459.0,4.0,4747.0,21.0,4124.0,53.0,2076.0,147.0,1119.0,230.0
266,2020-10-26,25,94,25955,1593,23905,457,12080.0,244.0,13875.0,...,3481.0,4.0,4769.0,21.0,4135.0,53.0,2079.0,147.0,1123.0,230.0
267,2020-10-27,16,72,26043,1602,23981,460,12121.0,246.0,13922.0,...,3495.0,4.0,4792.0,21.0,4148.0,53.0,2083.0,149.0,1127.0,231.0
268,2020-10-28,7,96,26146,1612,24073,461,12167.0,247.0,13979.0,...,3512.0,4.0,4812.0,21.0,4157.0,53.0,2090.0,150.0,1132.0,231.0

In [30]:
df = pd.merge(df, df_area, how='outer',on='date')

In [31]:
# df.isnull().sum()

In [32]:
df = df.fillna(0)

In [33]:
df.dtypes

date             object
overseas          int64
domestic          int64
confirmed         int64
iso               int64
                 ...
qs_domestic     float64
qs_confirmed    float64
qs_iso          float64
qs_iso_rel      float64
qs_death        float64
Length: 137, dtype: object

In [34]:
df['seoul_overseas'].dtypes

dtype('float64')

In [35]:
df = df.astype({'date':'datetime64','m_confirmed':'int64', 'm_death':'int64', 'f_confirmed':'int64', 'f_death':'int64',
               '0s_confirmed':'int64', '0s_death':'int64', '10s_confirmed':'int64', '10s_death':'int64',
               '20s_confirmed':'int64', '20s_death':'int64', '30s_confirmed':'int64', '30s_death':'int64',
               '40s_confirmed':'int64', '40s_death':'int64', '50s_confirmed':'int64', '50s_death':'int64',
               '60s_confirmed':'int64', '60s_death':'int64', '70s_confirmed':'int64', '70s_death':'int64',
               '80s_over_confirmed':'int64', '80s_over_death':'int64',
                'seoul_overseas':'int64','seoul_domestic':'int64','seoul_confirmed':'int64','seoul_iso':'int64','seoul_iso_rel':'int64','seoul_death':'int64',
                'bs_overseas':'int64','bs_domestic':'int64','bs_confirmed':'int64','bs_iso':'int64','bs_iso_rel':'int64','bs_death':'int64',
                'tk_overseas':'int64','tk_domestic':'int64','tk_confirmed':'int64','tk_iso':'int64','tk_iso_rel':'int64','tk_death':'int64',
                'ic_overseas':'int64','ic_domestic':'int64','ic_confirmed':'int64','ic_iso':'int64','ic_iso_rel':'int64','ic_death':'int64',
                'kj_overseas':'int64','kj_domestic':'int64','kj_confirmed':'int64','kj_iso':'int64','kj_iso_rel':'int64','kj_death':'int64',
                'dj_overseas':'int64','dj_domestic':'int64','dj_confirmed':'int64','dj_iso':'int64','dj_iso_rel':'int64','dj_death':'int64',
                'ulsan_overseas':'int64','ulsan_domestic':'int64','ulsan_confirmed':'int64','ulsan_iso':'int64','ulsan_iso_rel':'int64','ulsan_death':'int64',
                'sj_overseas':'int64','sj_domestic':'int64','sj_confirmed':'int64','sj_iso':'int64','sj_iso_rel':'int64','sj_death':'int64',
                'gg_overseas':'int64','gg_domestic':'int64','gg_confirmed':'int64','gg_iso':'int64','gg_iso_rel':'int64','gg_death':'int64',
                'kw_overseas':'int64','kw_domestic':'int64','kw_confirmed':'int64','kw_iso':'int64','kw_iso_rel':'int64','kw_death':'int64',
                'cb_overseas':'int64','cb_domestic':'int64','cb_confirmed':'int64','cb_iso':'int64','cb_iso_rel':'int64','cb_death':'int64',
                'cn_overseas':'int64','cn_domestic':'int64','cn_confirmed':'int64','cn_iso':'int64','cn_iso_rel':'int64','cn_death':'int64',
                'jb_overseas':'int64','jb_domestic':'int64','jb_confirmed':'int64','jb_iso':'int64','jb_iso_rel':'int64','jb_death':'int64',
                'jn_overseas':'int64','jn_domestic':'int64','jn_confirmed':'int64','jn_iso':'int64','jn_iso_rel':'int64','jn_death':'int64',
                'kb_overseas':'int64','kb_domestic':'int64','kb_confirmed':'int64','kb_iso':'int64','kb_iso_rel':'int64','kb_death':'int64',
                'kn_overseas':'int64','kn_domestic':'int64','kn_confirmed':'int64','kn_iso':'int64','kn_iso_rel':'int64','kn_death':'int64',
                'jj_overseas':'int64','jj_domestic':'int64','jj_confirmed':'int64','jj_iso':'int64','jj_iso_rel':'int64','jj_death':'int64',
                'qs_overseas':'int64','qs_domestic':'int64','qs_confirmed':'int64','qs_iso':'int64','qs_iso_rel':'int64','qs_death':'int64'
               })

In [36]:
df.dtypes

date            datetime64[ns]
overseas                 int64
domestic                 int64
confirmed                int64
iso                      int64
                     ...
qs_domestic              int64
qs_confirmed             int64
qs_iso                   int64
qs_iso_rel               int64
qs_death                 int64
Length: 137, dtype: object

In [37]:
df.to_csv("all_data.csv", index=False)